# Generated by Django 3.2 on 2023-06-20 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conpi_reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('code', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('code', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('code', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lims.province')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='conpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(blank=True, max_length=5000, null=True)),
                ('title_deed_number', models.CharField(blank=True, max_length=5000, null=True)),
                ('farm_category', models.CharField(blank=True, max_length=5000, null=True)),
                ('farm_owner_name', models.CharField(blank=True, max_length=5000, null=True)),
                ('name_of_applicant', models.CharField(blank=True, max_length=5000, null=True)),
                ('contact_details', models.CharField(blank=True, max_length=5000, null=True)),
                ('settlers', models.BooleanField(blank=True, null=True)),
                ('number_of_settlers', models.IntegerField(blank=True, null=True)),
                ('reasons_for_conpi', models.TextField(blank=True, null=True)),
                ('signatue', models.FileField(blank=True, null=True, upload_to='signature')),
                ('other', models.FileField(blank=True, null=True, upload_to='other_conpi_documents')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lims.district')),
                ('reason_for_applying', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lims.conpi_reasons')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
