# Generated by Django 3.2 on 2023-06-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lims', '0002_auto_20230620_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='conpi_status',
            new_name='conpi_stages',
        ),
        migrations.AddField(
            model_name='conpi',
            name='interestinterest',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
